server {
    listen 80;
    server_name stargio.com.br www.stargio.com.br;

    return 301 http://stargio.xyz$request_uri;
}

server {
    listen 80;
    server_name stargio.xyz www.stargio.xyz;

    root /stargio;
    index index.php index.html index.htm;

    access_log /var/log/nginx/stargio.access.log;
    error_log /var/log/nginx/stargio.error.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.1-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include fastcgi_params;
    }

    location ~ /\. {
        deny all;
    }
}
